export const LOCALIZATION = {
  en: {
    header: {
      createNewBoardBtn: 'Create New Board',
    },
    boardPage: {
      title: 'Boards',
    },
    singleBoardPage: {
      title: 'Boards',
      createColumnBtn: 'Create a column',
    },
    editProfilePage: {
      btnBack: 'back',
      title: 'Edit your profile',
      nameFieldLabel: 'Name',
      loginFieldLabel: 'Login',
      passFieldLabel: 'Password',
      confPassFieldLabel: 'Confirm Password',
      nameFieldErr: 'Please enter your name',
      loginFieldErr1: 'Please enter a login email',
      loginFieldErr2: 'The login email is invalid',
      passFieldErr: "Your password isn't strong enough",
      confPassFieldErr1: "The entered password doesn't match",
      confPassFieldErr2: 'Please enter a password',
      editBtn: 'Edit',
      delProfileBtn: 'Delete profile',
    },
    form: {
      btnCreateNewBoard: {
        title: 'Create Board',
        nameFieldLabel: 'Board Name',
        nameFieldErr: 'Please enter a board name',
        descriptionField: 'Board Description',
        descriptionFieldErr: 'Please enter a board description',
        formBtn: 'Create Board',
      },
      createColumn: {
        title: 'Create Column',
        nameFieldLabel: 'Column Name',
        nameFieldPlaceHolder: 'Enter Column Name',
        nameFieldErr: 'Please enter a column name',
        btnCreateColumn: 'Create Column',
      },
      createTask: {
        title: 'Create Task',
        nameFieldLabel: 'Task Name',
        nameFieldPlaceHolder: 'Enter Task Name',
        nameFieldErr: 'Please enter a task name',
        sizeFieldLabel: 'Task Size',
        sizeOptions: {
          tiny: 'Tiny',
          small: 'Small',
          medium: 'Medium',
          large: 'Large',
          xLarge: 'X-large',
        },
        priorityFieldLabel: 'Task Priority',
        priorityOptions: {
          low: 'Low',
          medium: 'Medium',
          high: 'High',
          urgent: 'Urgent',
        },
        descriptionFieldLabel: 'Description',
        createTaskBtn: 'Create Task',
      },
      editTask: {
        title: 'Edit Task',
        nameFieldLabel: 'Task Name',
        nameFieldPlaceHolder: 'Enter Task Name',
        nameFieldErr: 'Please enter a task name',
        sizeFieldLabel: 'Task Size',
        sizeOptions: {
          tiny: 'Tiny',
          small: 'Small',
          medium: 'Medium',
          large: 'Large',
          xLarge: 'X-large',
        },
        priorityFieldLabel: 'Task Priority',
        priorityOptions: {
          low: 'Low',
          medium: 'Medium',
          high: 'High',
          urgent: 'Urgent',
        },
        descriptionFieldLabel: 'Description',
        createTaskBtn: 'Edit Task',
      },
    },
  },
  ru: {
    header: {
      createNewBoardBtn: 'Создать новую доску',
    },
    boardPage: {
      title: 'Доски',
    },
    singleBoardPage: {
      title: 'Доски',
      createColumnBtn: 'Создать колонку',
    },
    editProfilePage: {
      btnBack: 'назад',
      title: 'Редактировать профиль',
      nameFieldLabel: 'Имя',
      loginFieldLabel: 'Логин',
      passFieldLabel: 'Пароль',
      confPassFieldLabel: 'Подтвердите пароль',
      nameFieldErr: 'Пожалуйста введите имя',
      loginFieldErr1: 'Пожалуйста введите логин - email',
      loginFieldErr2: 'Не верный логин',
      passFieldErr: 'Ваш пароль недостаточно надежен',
      confPassFieldErr1: 'Пароли не совпадают',
      confPassFieldErr2: 'Пожалуйста введите пароль',
      editBtn: 'Редактировать',
      delProfileBtn: 'Удалить профиль',
    },
    form: {
      btnCreateNewBoard: {
        title: 'Создать доску',
        nameFieldLabel: 'Имя доски',
        nameFieldErr: 'Пожалуйста введите имя доски',
        descriptionField: 'Описание доски',
        descriptionFieldErr: 'Пожалуйста введите описание',
        formBtn: 'Создать доску',
      },
      createColumn: {
        title: 'Создать колонку',
        nameFieldLabel: 'Имя колонки',
        nameFieldPlaceHolder: 'Введите имя колонки',
        nameFieldErr: 'Пожалуйста введите имя колонки',
        btnCreateColumn: 'Создать колонку',
      },
      createTask: {
        title: 'Создать задачу',
        nameFieldLabel: 'Имя задачи',
        nameFieldPlaceHolder: 'Введите имя задачи',
        nameFieldErr: 'Пожалуйста введите имя задачи',
        sizeFieldLabel: 'Размер задачи',
        sizeOptions: {
          tiny: 'Крошечная',
          small: 'Маленькая',
          medium: 'Средняя',
          large: 'Большая',
          xLarge: 'Очень большая',
        },
        priorityFieldLabel: 'Приоритет',
        priorityOptions: {
          low: 'Низкий',
          medium: 'Средний',
          high: 'Высокий',
          urgent: 'Срочная',
        },
        descriptionFieldLabel: 'Описание',
        createTaskBtn: 'Создать задачу',
      },
      editTask: {
        title: 'Редактировать задачу',
        nameFieldLabel: 'Имя задачи',
        nameFieldPlaceHolder: 'Введите имя задачи',
        nameFieldErr: 'Пожалуйста введите имя задачи',
        sizeFieldLabel: 'Размер задачи',
        sizeOptions: {
          tiny: 'Крошечная',
          small: 'Маленькая',
          medium: 'Средняя',
          large: 'Большая',
          xLarge: 'Очень большая',
        },
        priorityFieldLabel: 'Приоритет',
        priorityOptions: {
          low: 'Низкий',
          medium: 'Средний',
          high: 'Высокий',
          urgent: 'Срочная',
        },
        descriptionFieldLabel: 'Описание',
        createTaskBtn: 'Сохранить изменения',
      },
    },
  },
};
